name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  story_cms_client:
    path: ../
  http: ^1.6.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
